gilbsgilbs/babel-plugin-i18next-extract

.eslintrc.yml, .gitignore, README.md, src/config.ts, src/exporter.ts, src/plugin.ts, tests/exporter.test.ts
This was quite challenging since Babel calls the visitor for each
transpiled file, without giving the bigger picture. When processing a
file, we can't know if it's the last: we have to merge and write the
JSON files after each file.
Also:
- Rename `exporterJsonSpace` option to `jsonSpace`. The fact that it
was used in the exporter was an implementation detail.
- Remove global variables. Keep them in a state.
cc @rpCal
=> Add an option to discard old keys from JSON files. (Closes #8)

src/extractors/withTranslationHOC.ts, tests/__fixtures__/testWithTranslationHOC/scope.js, tests/__fixtures__/testWithTranslationHOC/scope.json
When a function was declared in an array, the plugin would crash.
=> Fix bug with withTranslationHOC and weird scopes.

src/extractors/tFunction.ts, tests/__fixtures__/testTFunction/withOpts.js, tests/__fixtures__/testTFunction/withOpts.json
When the second argument of the t function is just a string, the program
would crash. It's actually possible to specify a default value as a
string and not in an object.
See https://www.i18next.com/translation-function/essentials#passing-a-default-value
Fixes #21
ping @DanielHuisman
=> Fix crash with t function default value.

src/plugin.ts, tests/__fixtures__/testUseTranslationHook/namespace.js, tests/__fixtures__/testUseTranslationHook/namespace.json
The bug was introduced in #15 and was related to the keys priority
mechanism. When adding a key from useTranslation hook extractor, any
subsequent key coming from the same useTranslation hook would be
considered as conflicting.
Fixes #29
=> Fix skipped keys with useTranslation hook.

package.json, yarn.lock
When attempting to install this package, the node dependency fails to install on an NFS mount. The issue is due to https://github.com/aredridel/node-bin-setup/blob/master/index.js#L53. It's not possible to create a hard link on an NFS mount so this step fails in my team's environment. The referenced package _could_ also use a symlink instead of a hard link, but I think it'd be better to just remove this dependency entirely. There is a [2 year old PR](https://github.com/aredridel/node-bin-setup/pull/1) open in the repository to fix the issue but it hasn't been merged.
=> remove node depedency

src/exporters/jsonv3.ts, tests/exporters/jsonv3.test.ts
By default, JSON files created by the JSON exporter will also have a
trailing newline in order to be POSIX compliant. Though if the
whitespace is stripped at a later point in time by user, the exporter
will leave it as is.
Fixes #59
Closes #58
ping @michelts
=> Make JSONv3 exporter preserve whitespaces.

azure-pipelines.yml
This stopped working at some point and introduce a slight security risk
should the token was compromised from the CI server at some point.
I'll do manual releases from now on.
Fixes #66
=> Get rid of automated deployment.

docs/templates/configuration.md.yml, src/config.ts, src/extractors/commons.ts, src/extractors/transComponent.ts, tests/__fixtures__/testTransComponent/bindings.js, tests/__fixtures__/testTransComponent/keepBasicHtmlNode.js, tests/__fixtures__/testTransComponent/keepBasicHtmlNode.json, tests/__fixtures__/testTransComponent/nodeConversion.js, tests/__fixtures__/testTransComponent/nodeConversion.json
@culshaw, could you check if this indeed fixes your issue?
---
In Trans components, tag names that are specified in "transKeepBasicHtmlNodesFor" should not be converted to indices when they have no attributes. As react-i18next actually sets a few tags in this option by default, not supporting this option was quite annoying. See https://react.i18next.com/latest/trans-component#additional-options-on-i-18-next-init
Also, it appeared that the conversion to indices was incorrect for self-closing tags such as `<hr />`. They were converted to `<0/>` when they should actually have been converted to `<0></0>`. However, self-closing tags present in `transKeepBasicHtmlNodesFor` must be converted to `<br/>` (and not `<br></br>`). This PR should make sure this is handled properly.
Fixes #83
=>  Support react-i18next "transKeepBasicHtmlNodesFor" option

src/extractors/commons.ts, src/extractors/getFixedTFunction.ts, src/extractors/i18nextInstance.ts, src/extractors/index.ts, src/plugin.ts, tests/__fixtures__/testGetFixedTFunction/comments.js, tests/__fixtures__/testGetFixedTFunction/comments.json, tests/__fixtures__/testGetFixedTFunction/customNames.js, tests/__fixtures__/testGetFixedTFunction/customNames.json, tests/__fixtures__/testGetFixedTFunction/namespace.js, tests/__fixtures__/testGetFixedTFunction/namespace.json, tests/__fixtures__/testGetFixedTFunction/scopes.js, tests/__fixtures__/testGetFixedTFunction/scopes.json
=> Added `getFixedT()` Namespace Extractor

src/extractors/transComponent.ts, tests/__fixtures__/testTransComponent/keepBasicHtmlNode.js, tests/__fixtures__/testTransComponent/keepBasicHtmlNode.json, tests/__fixtures__/testTransComponent/nodeConversion.json
This commit adds a better heuristic to detect which Trans component will
be converted to indices by react-i18next (when using
transKeepBasicHtmlNodes which is enabled by default). In particular, if
the node has many children or interpolation, react-i18next ignores the
transKeepBasicHtmlNodes option and converts the node to indices.
Fixes #108
---
@pcorpet could you have a look? Does this indeed fix #108? It was quite complex to align with every edge-case statically, but this is the best heuristic I could make. I have not been able to fool it so far.
=> Fix bad extracted keys with Trans and basic HTML nodes.

src/extractors/withTranslationHOC.ts, tests/__fixtures__/testWithTranslationHOC/tNotCallee.js, tests/__fixtures__/testWithTranslationHOC/tNotCallee.json
When t is an argument not the callee, the extractor used to get it wrong.
=> Fix extraction of calls in withTranslation HOC

docs/templates/configuration.md.yml, src/config.ts, src/exporters/index.ts, tests/__fixtures__/testConfig/outputPath.config.js, tests/__fixtures__/testConfig/severalDomain.js, tests/runner.ts
Config: outputPath function support
I would like to have the control over the outputPath value so it can directly writes changes to a specific locale file.
```typescript
type outputPath = string | (locale: string, namespace: string) => string
```
**That option will only be available for javascript babel config file**
In our application locales cannot be extracted into the same folder because they are shared across the app.
Its only after our build we copy every locales to the same folder (`public/locales/`)
**Example: Folder structure**
```
.
└── src/
├── locales/
│   ├── en/
│   └── fr/
│       └── common.json
├── pages/
│   └── Dashboard/
│       └── locales/
│           ├── en/
│           └── fr/
│               └── dashboard.json
└── anotherFolder/
└── locales/
├── en/
└── fr/
└── …
```
=> feat(config): outputPath function support

package.json, src/exporters/index.ts, tests/exporters/exporter.test.ts
fixes #78
Add caching abilities to check if :
- translation file as change and must be updated in cache (based on last modified time)
- if the old version does not equal the actual we update the translation file (base on `originalTranslationFile` & `translationFile variable`)
Environment: `development`
Tool:
* Webpack (with watch option)
* babel-loader
* babel-plugin-i18next-extract
Our problem is the plugin re-write the translation file using the version it had at build time.
Example:
locale.json
```json
{
"foo": ""
}
```
build ->  the plugin has the key 'foo' and the value ''
Inside locale.json I change the value of `foo` with `easy` and I save the file.
locale.json
```json
{
"foo": "easy"
}
```
I add a key in my view named 'toto', the plugin extract that new key and add it inside our …
=> fix(exporter): fix cache overwriting changes to translation files

src/keys.ts, tests/__fixtures__/icu/icuPlurals.json
ICU plural extraction produces invalid value because of missing trailing `}`. It is not related to #184 even though it happens in same area.
This PR just simply adds the missing `}`
To double check if it is correct you can use https://devpal.co/icu-message-editor/ and copy the test fixture result in there
=> Fix: ICU plural extraction produces invalid syntax

CONTRIBUTING.md, README.md, docs/templates/configuration.md.yml, src/config.ts, src/exporters/index.ts, src/exporters/json.ts, src/index.ts, src/keys.ts, tests/__fixtures__/icu/icuPlurals.json, tests/__fixtures__/icu/jsonv3.js, tests/__fixtures__/icu/jsonv3.json, tests/__fixtures__/testLocale/plurals.json, tests/__fixtures__/testLocale/pluralsJSONv4.js, tests/__fixtures__/testLocale/pluralsJSONv4.json, tests/__fixtures__/testLocale/unknownJSONv4.js, tests/__fixtures__/testLocale/unknownJSONv4.json, tests/exporters/json.test.ts
Also force using JSONv4 for ICU as it makes the plural categories more
correct. This is technically a breaking change, but as the feature was
explicitely marked as expermiental, I wouldn't worry too much.
I have yet to decide if JSONv4 should be made the default now (which
would require a major version increase). We surely want new users to use
JSONv4 by default, but a major version increase might be an opportunity
to include other changes.
closes #203
=> feat: add support for JSONv4

src/plugin.ts
To fix #208 
I found the `exporterCache` object doesn't persist across all the runs in newer babel versions(7.16.10+).
After some runs, it becomes empty. 
The solution is inspired by https://github.com/babel/babel/discussions/13590#discussioncomment-1034864
It points out that the cache object needs to be put outside the plugin function. (maybe we can also consider to use `weakMap` for the performance improvement.)
```js
post() {
const extractState = this.I18NextExtract;
if (extractState.extractedKeys.length === 0) return;
console.log("exporterCache")
console.log(exporterCache)
// ... rest
},
```
|Before | After|
|---|---|
|![image](https://user-images.githubusercontent.com/6767433/182017717-490042dc-eac6-4a8a-89af-49fa8eb5303d.png)|![image](https://user-images.githubusercontent.com/6767433 …
=> Fix empty transpiled file cache issue

src/keys.ts, tests/__fixtures__/testLocale/pluralsJSONv4.json
To fix #256 
For {language}-{region} format locale, the plural count key can't be generated correctly.
The `locale` from the result of `pluralRule.resolvedOptions();` may only contain the language part, without the region.
Although the value of `locale` should be BCP 47 language tag, but node(only tested on v18.17) and some browsers don't support it yet. So I think we can also compare the language part of the locale.
On node v18.17
```js
const pluralRules = new Intl.PluralRules('en-US');
const options = pluralRules1.resolvedOptions();
console.log(options);
// output: Object { locale: "en", type: "cardinal",....}
```
=> Fix plural issue with lang-region locale

package.json
Recent versions of yarn refuse to publish packages that don't have a yarn.lock and are located within an existing workspace. If we create an empty yarn.lock, yarn still insists on locking the dependencies, which we definitely don't want to include in the output package.
Always use npm to publish package. I guess using yarn for anything makes little sense nowadays, so we might just want to drop it entirely at some point.
See #260
=> fix: don't use yarn to publish package

src/extractors/getFixedTFunction.ts, src/extractors/tFunction.ts, src/extractors/transComponent.ts, src/extractors/useTranslationHook.ts, src/keys.ts, tests/__fixtures__/testGetFixedTFunction/keyPrefix.js, tests/__fixtures__/testGetFixedTFunction/keyPrefix.json, tests/__fixtures__/testUseTranslationHook/keyPrefix.js, tests/__fixtures__/testUseTranslationHook/keyPrefix.json, tests/__fixtures__/testUseTranslationHook/simple.js, tests/__fixtures__/testUseTranslationHook/simple.json, tests/helpers.ts
Support optional keyPrefix option
https://www.i18next.com/overview/api#getfixedt
https://react.i18next.com/latest/usetranslation-hook#optional-keyprefix-option
Resolves #223
=> Support keyPrefix

.github/workflows/main.yml
CI was failing, probably because of a change in the setup-node action:
https://github.com/gilbsgilbs/babel-plugin-i18next-extract/actions/runs/7363053375/job/20042120587?pr=264
See also https://github.com/actions/setup-node/issues/480#issuecomment-1820622085
=> fix(ci): fix corepack setup fail

src/extractors/useTranslationHook.ts, tests/__fixtures__/testCustomHook/customNames.js, tests/__fixtures__/testCustomHook/customNames.json
Using custom `t` names combined with custom translation hooks is not working as expected.
For example, the translation keys will not be extracted:
```JSX
function MyComponent() {
const { myTranslationFunction } = useMyTranslationHook('namespace');
return <p>{myTranslationFunction('myTranslationKey')}</p>;
}
```
After some investigation, I found this is due to a hardcoded `"t"` key inside the `useTranslationHook` extractor:
https://github.com/gilbsgilbs/babel-plugin-i18next-extract/blob/7cc5b807de142bedabcacb234ecc167e9db343a1/src/extractors/useTranslationHook.ts#L59
This PR adds some simple logic to try out different function names in the order they are defined in the `tFunctionNames` configuration parameter
=> Fix: Add support to custom t names on custom translation hooks
